package com.masai;

public class Demo {
	
	//Q1. What is the Difference between Web Application and Web-services?
	
	//web application is that application which is run on web severer or run with the help of browser.
	//e.g: Gmail
	//Web-services is also a type of Web Application, that can generate dynamic result as raw data(json, xml, text) instead of
	//generating a html response (webpage)
    //Web Application generates the view(webpage) whereas Web-services generates raw data.
    //this raw data generated by the Web-services can be reused inside any other Web Application or 
	//any other type of application developed in any technology.
	
	
	
	//Q2.Difference between static and dynamic web-pages
	//1.static webpages : here content will be fixed for each user intraction, they are precreated (before client request) ex: home page of gmail.
    //the webresources which can generate static webpages are called static webresource program ex: html file
    //image file, etc.
	//2.dynamic webpages: page contents will changed dynamically based on the input given by the user. ex: inbox of Gmail.
    ///they are not precreated before client request, they will be created based on the input value given by the client dynamically.
    ///the webresources which can generate dynamic webpages are called dynamic webresource program ex:  Servlet program(it is a java class which implements Servlet interface), jsp file.
	
	//Q3. Explain http request structure, Alos explain what are headers in http request.
	//http request structure has following 3 subparts are there
	//1.initial request line
	//initial request has 3 parts:
	//1.https methods(get(),pu(),delete(),post())
	//2.Universal Resource Identifier(index.html) i.e home page
	//3.http version
	//2.request headers:these key value pairs 
	//1. Date : date and time on which request is made from the client.
	//2. Host: ipaddress of the client.
	//3. user-agent: from which browser the client has generated the request.
	//4.content-type: type of the data coming from the request body (json, txt, xml, pdf, jpg)
	//5.connection : live or lost
	//6.cockies: name-value pair text  
    //we can create our headers also 
	//3.Request body:it has data in JASON/XML format
	

}
